# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the fst step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.pi)
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

3.141592653589793
-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,9,1)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[0 1 2 3 4 5 6 7 8]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.23303401 0.02447376 0.05497306 0.53125816 0.91057158]
 [0.7246845  0.57245148 0.31809755 0.9803064  0.98123449]
 [0.99912476 0.08214993 0.12234529 0.66250383 0.89659128]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]

[[-1.48570689 -0.57314154  0.99970501  0.19320329  0.22864653]
 [ 0.87478861  0.11433042  1.22906158 -0.78526212  0.87410083]
 [ 0.3167162   1.4485664   0.89504176  0.97398582  0.33664274]
 [-0.33031458 -0.50123285 -1.13226769 -0.40252776  2.36411694]
 [ 0.63309403 -0.27732305 -0.76395069 -0.65659937  1.08439321]
 [ 0.45208692  0.56219634  0.54160522  2.04357516  0.02410915]
 [ 1.07673117 -0.44650929  0.41907558 -0.48861871 -0.53785718]
 [-0.37500697 -0.79475791 -0.02269281 -0.86450734 -1.27640891]
 [ 0.88577916 -0.91145622 -0.07649006 -0.77846216 -0.10280958]
 [-1.71754634 -0.4429467  -1.47925702 -1.62020188 -0.00341789]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5610882448921821
0.9145054344678551


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.024473762668530075
2.3641169406356024


In [14]:
# break here for next video!

In [43]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(6)
print(rand_vec)
print(rand_vec[1])

[-0.4106688   0.77925958  0.91338023  0.33870312 -0.81878062 -0.35087144]
0.7792595781454712


In [44]:
# we can access multiple entries at once using :
print(rand_vec[1:3])

[0.77925958 0.91338023]


In [46]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,3,1))
print(rand_vec[np.arange(0,3,1)])

[0 1 2]
[-0.4106688   0.77925958  0.91338023]


In [47]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[3.         3.         3.         0.53125816 0.91057158]
 [3.         3.         3.         0.         0.        ]
 [0.99912476 0.08214993 0.12234529 0.         0.        ]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]
3.0
3.0


In [19]:
print(rand_mat[0:2,1:3])

[[0.02447376 0.05497306]
 [0.57245148 0.31809755]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-0.40523519  1.44265033 -0.17069054 -0.06339381 -0.2265411   0.07485994
  0.32042429  0.23184054 -0.40846709 -0.15401763  2.27293504 -0.17435673
 -0.03584381  0.28559377 -0.08772563  2.02993397  0.14357992 -0.48790616
  1.00676041]

[-0.40523519  1.44265033 -0.17069054  4.          4.          0.07485994
  0.32042429  0.23184054 -0.40846709 -0.15401763  2.27293504 -0.17435673
 -0.03584381  0.28559377 -0.08772563  2.02993397  0.14357992 -0.48790616
  1.00676041]

[-0.40523519  1.44265033 -0.17069054  1.          2.          0.07485994
  0.32042429  0.23184054 -0.40846709 -0.15401763  2.27293504 -0.17435673
 -0.03584381  0.28559377 -0.08772563  2.02993397  0.14357992 -0.48790616
  1.00676041]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.23303401 0.02447376 0.05497306 0.53125816 0.91057158]
 [0.7246845  0.57245148 0.31809755 0.9803064  0.98123449]
 [0.99912476 0.08214993 0.12234529 0.66250383 0.89659128]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]

[[0.23303401 0.02447376 0.05497306 0.53125816 0.91057158]
 [0.7246845  0.57245148 0.31809755 0.         0.        ]
 [0.99912476 0.08214993 0.12234529 0.         0.        ]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.23303401 0.02447376 0.05497306]
 [0.7246845  0.57245148 0.31809755]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.53125816 0.91057158]
 [3.         3.         3.         0.         0.        ]
 [0.99912476 0.08214993 0.12234529 0.         0.        ]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.53125816 0.91057158]
 [3.         3.         3.         0.         0.        ]
 [0.99912476 0.08214993 0.12234529 0.         0.        ]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]


In [25]:
# break here for next video

In [57]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.72429915  1.71827969 -1.00823865 -0.1016748  -0.4613289   1.22885895
 -0.92270906 -0.92566226 -0.40377949  0.4914428  -0.83206919  0.78463856
 -0.85263518 -1.53372696 -1.35188076]
[False  True False False False  True False False False  True False  True
 False False False]
[1.71827969 1.22885895 0.4914428  0.78463856]


In [51]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-1.48570689 -0.57314154  0.99970501  0.19320329  0.22864653]
 [ 0.87478861  0.11433042  1.22906158 -0.78526212  0.87410083]
 [ 0.3167162   1.4485664   0.89504176  0.97398582  0.33664274]
 [-0.33031458 -0.50123285 -1.13226769 -0.40252776  2.36411694]
 [ 0.63309403 -0.27732305 -0.76395069 -0.65659937  1.08439321]
 [ 0.45208692  0.56219634  0.54160522  2.04357516  0.02410915]
 [ 1.07673117 -0.44650929  0.41907558 -0.48861871 -0.53785718]
 [-0.37500697 -0.79475791 -0.02269281 -0.86450734 -1.27640891]
 [ 0.88577916 -0.91145622 -0.07649006 -0.77846216 -0.10280958]
 [-1.71754634 -0.4429467  -1.47925702 -1.62020188 -0.00341789]]
[0.99970501 0.19320329 0.22864653 0.87478861 0.11433042 1.22906158
 0.87410083 0.3167162  1.4485664  0.89504176 0.97398582 0.33664274
 2.36411694 0.63309403 1.08439321 0.45208692 0.56219634 0.54160522
 2.04357516 0.02410915 1.07673117 0.41907558 0.88577916]


In [52]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.4106688   0.77925958  0.91338023  0.33870312 -0.81878062 -0.35087144]

[-0.4106688  -5.         -5.          0.33870312 -0.81878062 -0.35087144]


In [55]:
# let's save some arrays on the disk for use later!
np.save('r_saved_file_name',rand_mat2)


In [56]:
np.savez('r_zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-1.48570689 -0.57314154  0.99970501  0.19320329  0.22864653]
 [ 0.87478861  0.11433042  1.22906158 -0.78526212  0.87410083]
 [ 0.3167162   1.4485664   0.89504176  0.97398582  0.33664274]
 [-0.33031458 -0.50123285 -1.13226769 -0.40252776  2.36411694]
 [ 0.63309403 -0.27732305 -0.76395069 -0.65659937  1.08439321]
 [ 0.45208692  0.56219634  0.54160522  2.04357516  0.02410915]
 [ 1.07673117 -0.44650929  0.41907558 -0.48861871 -0.53785718]
 [-0.37500697 -0.79475791 -0.02269281 -0.86450734 -1.27640891]
 [ 0.88577916 -0.91145622 -0.07649006 -0.77846216 -0.10280958]
 [-1.71754634 -0.4429467  -1.47925702 -1.62020188 -0.00341789]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.53125816 0.91057158]
 [3.         3.         3.         0.         0.        ]
 [0.99912476 0.08214993 0.12234529 0.         0.        ]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]

[[-1.48570689 -0.57314154  0.99970501  0.19320329  0.22864653]
 [ 0.87478861  0.11433042  1.22906158 -0.78526212  0.87410083]
 [ 0.3167162   1.4485664   0.89504176  0.97398582  0.33664274]
 [-0.33031458 -0.50123285 -1.13226769 -0.40252776  2.36411694]
 [ 0.63309403 -0.27732305 -0.76395069 -0.65659937  1.08439321]
 [ 0.45208692  0.56219634  0.54160522  2.04357516  0.02410915]
 [ 1.07673117 -0.44650929  0.41907558 -0.48861871 -0.53785718]
 [-0.37500697 -0.79475791 -0.02269281 -0.86450734 -1.27640891]
 [ 0.88577916 -0.91145622 -0.07649006 -0.77846216 -0.10280958]
 [-1.71754634 -0.4429467  -1.47925702 -1.62020188 -0.00341789]]
[[3.         3.         3.         0.53125816 0.91057158]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.53125816 0.91057158]
 [3.         3.         3.         0.         0.        ]
 [0.99912476 0.08214993 0.12234529 0.         0.        ]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]

[[3.         3.         3.         0.53125816 0.91057158]
 [3.         3.         3.         0.         0.        ]
 [0.99912476 0.08214993 0.12234529 0.         0.        ]
 [0.53900741 0.09896074 0.9957676  0.26723056 0.73722642]
 [0.02521241 0.79491665 0.68137736 0.90472857 0.88897833]]
