In [10]:
from random import choice
from numpy import array, dot, random

import numpy as np


In [15]:
# MCNeuron for And
w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]), 0),
    (array([1,0]), 0),
    (array([1,1]), 1),
]

step_function = lambda x: 0 if x < 2 else 1    # Step function with threshold of 2. Anything below is 0 

In [16]:
for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 0
[1 0]: 1.0 -> 0
[1 1]: 2.0 -> 1


In [17]:
# MCNeruon for OR
w = random.rand(2)
w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 0),
    (array([0,1]), 1),
    (array([1,0]), 1),
    (array([1,1]), 1),
]

step_function = lambda x: 0 if x < 1 else 1    # Step function with threshold of 1. Anything below is 0 


In [18]:
for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 0
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 1


In [19]:
# MCNeuron for NAND

step_function = lambda x: 0 if x >= 2 else 1    # Step function with threshold of > 2 is 0 

w[1] = 1
w[0] = 1

training_data = [
    (array([0,0]), 1),
    (array([0,1]), 1),
    (array([1,0]), 1),
    (array([1,1]), 0),
]

for x, _ in training_data:
    result = dot(x, w)

    print("{}: {} -> {}".format(x[:2], result, step_function(result)))


[0 0]: 0.0 -> 1
[0 1]: 1.0 -> 1
[1 0]: 1.0 -> 1
[1 1]: 2.0 -> 0


In [20]:
# Rosenblat's Perceptron included a way to adjust the weights and find the appropriate combinations 
# to overcome the need to modify thresholds for each gate separately, it used a bias term using which the thresholds in the 
# neuron can be modified to implement multiple Boolean functions in one code

In [21]:

step_function = lambda x: 0 if x < 100 else 1    # Step function with threshold of 0.5. Anything below is 0 


# AND gate
training_data = [
    (array([0,0 ,1]), 0),
    (array([0,1, 1]), 0),
    (array([1,0, 1]), 0),
    (array([1,1, 1]), 1),
]

w = random.rand(3)
print(w)

errors = []
eta = 0.1
n = 100000

for i in range(n):
    x, expected = choice(training_data)


    result = dot(w, x)
    error = expected - step_function(result)   # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                       # that is the beauty of bias. The 'AND' pattern is learnt from data
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))


[0.52088884 0.29131398 0.66582827]
[0 0 1]: 33.5658282679858 -> 0
[0 1 1]: 66.75714224941083 -> 0
[1 0 1]: 66.98671710986739 -> 0
[1 1 1]: 100.17803109129241 -> 1


In [22]:
# OR function in RB Neuron


step_function = lambda x: 0 if x < 100 else 1    # Step function with threshold of 0.5. Anything below is 0 


# AND gate
training_data = [
    (array([0,0 ,1]), 0),
    (array([0,1, 1]), 1),
    (array([1,0, 1]), 1),
    (array([1,1, 1]), 1),
]

w = random.rand(3)
b = .1    # initializing bias term
errors = []
eta = 0.1
n = 10000

for i in range(n):
    x, expected = choice(training_data)
    
   # w = np.append(w, b)

    result = dot(w, x)
    error = expected - step_function(result)   # irrespective of what threshold we set, the algo will find the approp weights
    errors.append(error)                       # that is the beauty of bias. The 'OR' pattern is learnt from data
    w += eta * error * x

for x, _ in training_data:
    result = dot(x, w)
    print("{}: {} -> {}".format(x[:3], result, step_function(result)))


[0 0 1]: 61.62622767552408 -> 0
[0 1 1]: 100.06488112397945 -> 1
[1 0 1]: 100.37734535228714 -> 1
[1 1 1]: 138.81599880074248 -> 1
